### ISSUE TITLE
tests fail

### ISSUE THREAD

**Issue by MohamadHarastani** [scipion-em/scipion-em-pyseg#60]
```
scipion3 tests
>>>> pyseg
Error loading the test. Please, run the test for more information: pyseg.tests.test_preseg_graphs_fils_picking
Error loading the test. Please, run the test for more information: pyseg.tests.test_posRec_classify2d
(base) harastamadm@PC4-0002-D:/shared/scipion3/plugins$ scipion3 tests pyseg.tests.test_preseg_graphs_fils_picking
Scipion v3.0.12 - Eugenius
Running tests....
[   FAILED ] _FailedTest.test_preseg_graphs_fils_picking


Traceback (most recent call last):
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_preseg_graphs_fils_picking
Traceback (most recent call last):
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/shared/scipion3/plugins/scipion-em-pyseg/pyseg/tests/test_preseg_graphs_fils_picking.py", line 30, in <module>
    from pyseg.protocols.protocol_picking import PROJECTIONS
  File "/shared/scipion3/plugins/scipion-em-pyseg/pyseg/protocols/__init__.py", line 27, in <module>
    from .protocol_post_rec_particles import ProtPySegPostRecParticles
  File "/shared/scipion3/plugins/scipion-em-pyseg/pyseg/protocols/protocol_post_rec_particles.py", line 30, in <module>
    from pyseg.convert import readPysegSubtomograms
  File "/shared/scipion3/plugins/scipion-em-pyseg/pyseg/convert/__init__.py", line 26, in <module>
    from pyseg.convert.convert import PysegStarReader
  File "/shared/scipion3/plugins/scipion-em-pyseg/pyseg/convert/convert.py", line 31, in <module>
    from pyseg.utils import manageDims
  File "/shared/scipion3/plugins/scipion-em-pyseg/pyseg/utils.py", line 34, in <module>
    from reliontomo.constants import SHIFTX, SHIFTY, SHIFTZ, TILT, PSI, ROT
ImportError: cannot import name 'SHIFTX' from 'reliontomo.constants' (/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/reliontomo/constants.py)



[==========] run 1 tests (0.000 secs)

[  FAILED  ] 1 tests

[  PASSED  ] 0 tests

(base) harastamadm@PC4-0002-D:/shared/scipion3/plugins$ gedit /shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/reliontomo/constants.py
(base) harastamadm@PC4-0002-D:/shared/scipion3/plugins$ pyseg.tests.test_posRec_classify2d
pyseg.tests.test_posRec_classify2d: command not found
(base) harastamadm@PC4-0002-D:/shared/scipion3/plugins$ scipion3 tests pyseg.tests.test_posRec_classify2d
Scipion v3.0.12 - Eugenius
Running tests....
[   FAILED ] _FailedTest.test_posRec_classify2d


Traceback (most recent call last):
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_posRec_classify2d
Traceback (most recent call last):
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/shared/scipion3/plugins/scipion-em-pyseg/pyseg/tests/test_posRec_classify2d.py", line 34, in <module>
    from reliontomo.protocols import ProtImportSubtomogramsFromStar
ImportError: cannot import name 'ProtImportSubtomogramsFromStar' from 'reliontomo.protocols' (/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/reliontomo/protocols/__init__.py)



[==========] run 1 tests (0.000 secs)

[  FAILED  ] 1 tests

[  PASSED  ] 0 tests
```

**Comment by MohamadHarastani** [comment]
Okay after installing scipion-em-reliontomo it passed! The documentation says that the plugin Dynamo should be installed, but it should also say that the latest version of reliontomo plugin should be installed too.

Cheers
Mohamad

**Comment by MohamadHarastani** [comment]
It is true that I had gcc/g++ version 7 when I installed the plugin. I did that by relinking it manually. After the installation, I returned back to version 8. Before switching to version 7 the installation of the plugin fails.
If there is something that I can test from my side, let me know.
Cheers

**Comment by JorMaister** [comment]
Passing now. Current version admits the compiler gcc/g++ from 5 to 12, both included.
