### ISSUE TITLE
if there is no picked coordinates pyseg -picking protocol fails

### ISSUE THREAD

**Issue by Vilax** [scipion-em/scipion-em-pyseg#71]
00001:   project._getRelationGraph: parent Node is None: 786
00002:   project._getRelationGraph: parent Node is None: 786
00003:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:35: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00004:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00005:     eps=np.finfo(np.float).eps,
00006:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:597: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00007:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00008:     eps=np.finfo(np.float).eps, copy_X=True, fit_path=True,
00009:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:836: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00010:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00011:     eps=np.finfo(np.float).eps, copy_X=True, fit_path=True,
00012:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:862: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00013:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00014:     eps=np.finfo(np.float).eps, positive=False):
00015:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:1097: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00016:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00017:     max_n_alphas=1000, n_jobs=None, eps=np.finfo(np.float).eps,
00018:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:1344: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00019:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00020:     max_n_alphas=1000, n_jobs=None, eps=np.finfo(np.float).eps,
00021:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:1480: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00022:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00023:     eps=np.finfo(np.float).eps, copy_X=True, positive=False):
00024:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/linear_model/randomized_l1.py:152: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00025:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00026:     precompute=False, eps=np.finfo(np.float).eps,
00027:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/linear_model/randomized_l1.py:320: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00028:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00029:     eps=np.finfo(np.float).eps, random_state=None,
00030:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/linear_model/randomized_l1.py:580: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00031:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00032:     eps=4 * np.finfo(np.float).eps, n_jobs=None,
00033:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/decomposition/online_lda.py:31: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00034:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00035:     EPS = np.finfo(np.float).eps
00036:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:35: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00037:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00038:     eps=np.finfo(np.float).eps,
00039:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:597: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00040:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00041:     eps=np.finfo(np.float).eps, copy_X=True, fit_path=True,
00042:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:836: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00043:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00044:     eps=np.finfo(np.float).eps, copy_X=True, fit_path=True,
00045:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:862: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00046:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00047:     eps=np.finfo(np.float).eps, positive=False):
00048:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:1097: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00049:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00050:     max_n_alphas=1000, n_jobs=None, eps=np.finfo(np.float).eps,
00051:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:1344: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00052:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00053:     max_n_alphas=1000, n_jobs=None, eps=np.finfo(np.float).eps,
00054:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:1480: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00055:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00056:     eps=np.finfo(np.float).eps, copy_X=True, positive=False):
00057:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/linear_model/randomized_l1.py:152: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00058:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00059:     precompute=False, eps=np.finfo(np.float).eps,
00060:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/linear_model/randomized_l1.py:320: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00061:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00062:     eps=np.finfo(np.float).eps, random_state=None,
00063:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/linear_model/randomized_l1.py:580: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00064:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00065:     eps=4 * np.finfo(np.float).eps, n_jobs=None,
00066:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/decomposition/online_lda.py:31: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00067:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00068:     EPS = np.finfo(np.float).eps
00069:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:35: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00070:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00071:     eps=np.finfo(np.float).eps,
00072:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:597: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00073:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00074:     eps=np.finfo(np.float).eps, copy_X=True, fit_path=True,
00075:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:836: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00076:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00077:     eps=np.finfo(np.float).eps, copy_X=True, fit_path=True,
00078:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:862: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00079:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00080:     eps=np.finfo(np.float).eps, positive=False):
00081:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:1097: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00082:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00083:     max_n_alphas=1000, n_jobs=None, eps=np.finfo(np.float).eps,
00084:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:1344: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00085:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00086:     max_n_alphas=1000, n_jobs=None, eps=np.finfo(np.float).eps,
00087:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:1480: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00088:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00089:     eps=np.finfo(np.float).eps, copy_X=True, positive=False):
00090:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/linear_model/randomized_l1.py:152: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00091:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00092:     precompute=False, eps=np.finfo(np.float).eps,
00093:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/linear_model/randomized_l1.py:320: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00094:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00095:     eps=np.finfo(np.float).eps, random_state=None,
00096:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/linear_model/randomized_l1.py:580: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00097:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00098:     eps=4 * np.finfo(np.float).eps, n_jobs=None,
00099:   /home/tomo/anaconda3/envs/pySeg-v2.0.5/lib/python3.7/site-packages/sklearn/decomposition/online_lda.py:31: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
00100:   Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
00101:     EPS = np.finfo(np.float).eps
00102:   project._getRelationGraph: parent Node is None: 786
00103:   project._getRelationGraph: parent Node is None: 786
00104:   Couldn't run the code in a thread.
00105:   Traceback (most recent call last):
00106:     File "/home/tomo/scipion3/scipion-pyworkflow/pyworkflow/protocol/executor.py", line 148, in run
00107:       self.step._run()  # not self.step.run() , to avoid race conditions
00108:     File "/home/tomo/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 255, in _run
00109:       resultFiles = self._runFunc()
00110:     File "/home/tomo/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 251, in _runFunc
00111:       return self._func(*self._args)
00112:     File "/home/tomo/scipion3/Plugins/scipion-em-pyseg/pyseg/protocols/protocol_picking.py", line 194, in createOutputStep
00113:       raise Exception('ERROR! No coordinates were picked.')
00114:   Exception: ERROR! No coordinates were picked.
00115:   Protocol failed: ERROR! No coordinates were picked.

**Comment by JorMaister** [comment]
Yes, that error is thrown by us. We thought it should fail with that "ERROR! No coordinates were picked" message as there's no sense in a green protocol without particles picked. Do you have any suggestions regarding that?
