### ISSUE TITLE
installer not working if gcc is not within allowed range

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-pyseg#85]
https://github.com/scipion-em/scipion-em-pyseg/blob/f4500cecb8500c1938697626a41ccf6a00d5c23e/pyseg/__init__.py#L89

I have gcc-14. Instead of `echo "gcc-14 detected. g++-14 detected. Required conditions: [1] Both compilers version must be the same. [2] Compiler version must be in range [5, 12]."` I am getting:

```
gsharov@lvx-0855:~/soft/scipion-em-plugins/scipion-em-pyseg$ scipion3 installb pySeg
Scipion v3.7.1 - Eugenius
Error retrieving plugin pyseg binaries:  not enough values to unpack (expected 2, got 1)
This method will return the plugin class in the future. Please use getPluginModule instead
Couldn't get binaries definition of pyseg plugin: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/home/gsharov/soft/scipion3/scipion-app/scipion/install/plugin_funcs.py", line 334, in getInstallenv
    plugin.defineBinaries(env)
  File "/home/gsharov/soft/scipion-em-plugins/scipion-em-pyseg/pyseg/__init__.py", line 110, in defineBinaries
    env.addPackage(PYSEG,
  File "/home/gsharov/soft/scipion3/scipion-app/scipion/install/funcs.py", line 645, in addPackage
    for cmd, tgt in commands:
ValueError: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/home/gsharov/soft/scipion3/scipion-app/scipion/__main__.py", line 504, in <module>
    main()
  File "/home/gsharov/soft/scipion3/scipion-app/scipion/__main__.py", line 311, in main
    installPluginMethods()
  File "/home/gsharov/soft/scipion3/scipion-app/scipion/install/install_plugin.py", line 267, in installPluginMethods
    pinfo.installBin({'args': [binTarget, '-j', numberProcessor]})
  File "/home/gsharov/soft/scipion3/scipion-app/scipion/install/plugin_funcs.py", line 166, in installBin
    environment.execute()
  File "/home/gsharov/soft/scipion3/scipion-app/scipion/install/funcs.py", line 770, in execute
    raise RuntimeError("Unknown target: %s" % t)
RuntimeError: Unknown target: pySeg
Error at main: Unknown target: pySeg

```

**Comment by chris-hypercag** [comment]
I ran into this same issue. I just wanted to add that pyseg's `defineBinaries()` method in `__init__.py` checks for compiler compatibility but any resulting error message conflicts with the `addPackage` method which gives rise to the `ValueError: not enough values to unpack (expected 2, got 1)` error essentially burying the actual cause of the failure. To fix this proble the user has to dig through the methods mentioned in the traceback to determine that the error is actually causes by gcc versioning issue.  

The fix for this problem is better error handling in `defineBinaries()`
